spring:
  application.name: AI-Create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_creator
    username: root
    password: 123456
    # redis配置
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      ttl: 3600
      password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    # sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# Mybatis-Plus 配置
mybatis-plus:
  configuration:
    # 开启下划线到驼峰的自动映射
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

springdoc:
  api-docs:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus-latest
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3
    #     流式模型
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus-latest
      max-tokens: 8192
      log-requests: true
      log-responses: true
      max-retries: 3
#      智能路由模型
    routing-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus-latest
      max-tokens: 8192
      log-requests: true
      log-responses: true
      # 推理 AI 模型配置（用于复杂的推理任务）
    reasoning-streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API_KEY}
      model-name: qwen-plus-latest
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
# 阿里云 OSS 配置 (密钥通过环境变量读取)
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: akainews
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
  # RabbitMQ配置






